apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-report
  description: python app
  tags:
    - python
    - flask
    - postgresql
    - secure-by-default
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: devabm26/python-report
    dev.redhat.com/devspaces-url: https://devspaces.apps.cluster-6pfqs.6pfqs.sandbox2325.opentlc.com/#https://github.com/devabm26/python-report
  links:
    - url: https://github.com/devabm26/python-report
      title: View Source
      icon: github
    - url: https://devspaces.apps.cluster-6pfqs.6pfqs.sandbox2325.opentlc.com/#https://github.com/devabm26/python-report
      title: Open in DevSpaces
      icon: dashboard
spec:
  type: service
  lifecycle: production
  owner: user:default/arunhari82
  system: data-platform
  providesApis:
    - python-report-api

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: python-report-api
  description: REST API for python-report
spec:
  type: openapi
  lifecycle: production
  owner: user:default/arunhari82
  definition:
    $text: ./openapi.yaml
